### ISSUE TITLE
Error at calculate_chrom_snp_densities   step

### ISSUE THREAD

**Issue by emmannaemeka** [Gabaldonlab/jloh#2]
Hey,
I ran into this error and do not know how to proceed

jloh  extract --vcf /Users/emmannaemeka/Documents/cglabarata/cglbarata_analaysis/cglabara_analysis/ger_bam/jloh/b9_jlohcall_con.vcf --ref /Users/emmannaemeka/Documents/cglabarata/cglbarata_analaysis/cglabara_analysis/cbs138.fasta --bam  /Users/emmannaemeka/Documents/cglabarata/cglbarata_analaysis/cglabara_analysis/ger_bam/b9.bam
[Thu Apr 13 15:33:29 2023] Preparing workspace...
[Thu Apr 13 15:33:29 2023] Running in default mode...
[Thu Apr 13 15:33:29 2023] Extracting heterozygous and homozygous SNPs...
[Thu Apr 13 15:33:29 2023] Found 3410 heterozygous SNPs and 59669 homozygous SNPs
[Thu Apr 13 15:33:29 2023] Getting hetero- and homozygous SNP density...
Traceback (most recent call last):
  File "/Users/emmannaemeka/Documents/bioiformatics_program/jloh/src/extract", line 1464, in <module>
    main(args, tmp_bams)
  File "/Users/emmannaemeka/Documents/bioiformatics_program/jloh/src/extract", line 1450, in main
    run_in_default_mode(args, tmp_bams)
  File "/Users/emmannaemeka/Documents/bioiformatics_program/jloh/src/extract", line 1164, in run_in_default_mode
    hetero_div, homo_div = hetero_and_homo_snp_densities(Vcfs["hetero"][0], Vcfs["homo"][0], args.ref)
  File "/Users/emmannaemeka/Documents/bioiformatics_program/jloh/src/extract", line 390, in hetero_and_homo_snp_densities
    Het_snp_densities = calculate_chrom_snp_densities(Hetero_lines, ref)
  File "/Users/emmannaemeka/Documents/bioiformatics_program/jloh/src/extract", line 372, in calculate_chrom_snp_densities
    Snps_by_chrom[snp[0]].append(snp[1])
KeyError: 'chr_A'

**Comment by MatteoSchiavinato** [comment]
Is `chr_A` within the chromosome names contained in `/Users/emmannaemeka/Documents/cglabarata/cglbarata_analaysis/cglabara_analysis/cbs138.fasta`?

**Comment by emmannaemeka** [comment]
Yes, I git cloned and re-ran with same error

**Comment by MatteoSchiavinato** [comment]
Then you'll have to send me a minimal dataset that reproduces the error, because it isn't happening with my test data.
