### ISSUE TITLE
Error running jloh plot

### ISSUE THREAD

**Issue by nityendra21** [Gabaldonlab/jloh#8]
Hello, I am getting an error when running `jloh plot` on my dataset.
The command I used was: 
```./jloh plot --one-ref --loh jloh/jloh.LOH_blocks.tsv --het jloh/jloh.exp.het_blocks.bed --output-dir jloh/plot/```

The error that I'm getting is: 
```[Tue Oct 31 15:32:29 2023] Reading input information
[Tue Oct 31 15:32:29 2023] Quantizing heterozygosity in windows of 10000 bp
Parsing rows: 100.0%        
[Tue Oct 31 15:32:45 2023] Sorting by genome coordinate
[Tue Oct 31 15:32:46 2023] Quantizing intervals in windows of 10000 bp
Parsing rows: 100.0%        
[Tue Oct 31 15:33:41 2023] Sorting by genome coordinate
Traceback (most recent call last):
  File "/home/igib/jloh/jloh-1.0.2/src/plot", line 974, in <module>
    main(args)
  File "/home/igib/jloh/jloh-1.0.2/src/plot", line 964, in main
    run_oneref_mode(args)
  File "/home/igib/jloh/jloh-1.0.2/src/plot", line 905, in run_oneref_mode
    df = fill_missing_windows(df, "one_ref", args)
  File "/home/igib/jloh/jloh-1.0.2/src/plot", line 699, in fill_missing_windows
    df_new.columns = ["Sample", "Chromosome", "W_start", "W_end", "Het_pos", "Het_ratio", "LOH_pos", "LOH_ratio"]
  File "/home/igib/miniforge3/envs/jloh/lib/python3.7/site-packages/pandas/core/generic.py", line 5500, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "/home/igib/miniforge3/envs/jloh/lib/python3.7/site-packages/pandas/core/generic.py", line 766, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/igib/miniforge3/envs/jloh/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 216, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/igib/miniforge3/envs/jloh/lib/python3.7/site-packages/pandas/core/internals/base.py", line 58, in _validate_set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 0 elements, new values have 8 elements```

**Comment by MatteoSchiavinato** [comment]
This type of errors are hard to assess without a minimal reproducible dataset. Are you willing to send me the LOH_blocks and the het file from your setup?

**Comment by nityendra21** [comment]
Yes sure, please find the files in the MEGA link: https://mega.nz/folder/UdN0zSTA#1yc4NT2KifYmhbKgl3T2pA

**Comment by nityendra21** [comment]
Yes sure, please find the files in the MEGA link: https://mega.nz/folder/UdN0zSTA#1yc4NT2KifYmhbKgl3T2pA
